# Generated by Django 5.2.3 on 2025-06-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beggining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
