name: Django CI/CD

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest]


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: ['3.8','3.9','3.10','3.12']

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name : Run Tests
        run: |
          python manage.py test
